src/Entity/Artist.php
<?php

namespace App\Entity;

use App\Repository\ArtistRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=ArtistRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class Artist implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $lastname;

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=80)
     */
    private $pseudo;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $tattoo_shop;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=100, nullable=true)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $profile_picture;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $instagram;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="string", length=14, nullable=true)
     */
    private $siret;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $hide;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="artist", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @ORM\ManyToMany(targetEntity=Style::class, mappedBy="artist")
     */
    private $styles;
    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cover_picture;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activation_token;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reset_token;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lat;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lng;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isVerified;

  

    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->styles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(?string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(?string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getTattooShop(): ?string
    {
        return $this->tattoo_shop;
    }

    public function setTattooShop(?string $tattoo_shop): self
    {
        $this->tattoo_shop = $tattoo_shop;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getProfilePicture(): ?string
    {
        return $this->profile_picture;
    }

    public function setProfilePicture(?string $profile_picture): self
    {
        $this->profile_picture = $profile_picture;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getInstagram(): ?string
    {
        return $this->instagram;
    }

    public function setInstagram(?string $instagram): self
    {
        $this->instagram = $instagram;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(?string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getHide(): ?bool
    {
        return $this->hide;
    }

    public function setHide(?bool $hide): self
    {
        $this->hide = $hide;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setArtist($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getArtist() === $this) {
                $picture->setArtist(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Style[]
     */
    public function getStyles(): Collection
    {
        return $this->styles;
    }

    public function addStyle(Style $style): self
    {
        if (!$this->styles->contains($style)) {
            $this->styles[] = $style;
            $style->addArtist($this);
        }

        return $this;
    }

    public function removeStyle(Style $style): self
    {
        if ($this->styles->removeElement($style)) {
            $style->removeArtist($this);
        }

        return $this;
    }

   

    

    public function getCoverPicture(): ?string
    {
        return $this->cover_picture;
    }

    public function setCoverPicture(?string $cover_picture): self
    {
        $this->cover_picture = $cover_picture;

        return $this;
    }

    public function getActivationToken(): ?string
    {
        return $this->activation_token;
    }

    public function setActivationToken(?string $activation_token): self
    {
        $this->activation_token = $activation_token;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->reset_token;
    }

    public function setResetToken(?string $reset_token): self
    {
        $this->reset_token = $reset_token;

        return $this;
    }

    public function getLat(): ?string
    {
        return $this->lat;
    }

    public function setLat(string $lat): self
    {
        $this->lat = $lat;

        return $this;
    }

    public function getLng(): ?string
    {
        return $this->lng;
    }

    public function setLng(?string $lng): self
    {
        $this->lng = $lng;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

}

src/Controller/HomeController.php
<?php

namespace App\Controller;


use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use App\Form\RegistrationFormType;
use App\Form\ContactArtistType;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
use App\Entity\Artist;
use App\Entity\Style;
use Doctrine\ORM\Mapping\Id;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Component\Mailer\MailerInterface;



class HomeController extends AbstractController
{
    /**
     * @Route("/", name="home")
     */
    public function index(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new Artist();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);


        $entityManager = $this->getDoctrine()->getManager();
        $styles = $entityManager->getRepository(Style::class)->findAll();
        
        //j'affiche les nouveaux inscrits = par ordre d'ID, le plus grand ID est donc le dernier: limité à 4 affichages
        $artistes = $entityManager->getRepository(Artist::class)->findBy(
            array(),
            array('id' => 'DESC'), 4);
       

        // Formulaire de connexion
        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );


            $entityManager->persist($user);
            $entityManager->flush();
           
            // generate a signed url and email it to the user
            // $this->emailVerifier->sendEmailConfirmation('app_verify_email', $user,
            //     (new TemplatedEmail())
            //         ->from(new Address('finkart@outlook.fr', 'Fink Art'))
            //         ->to($user->getEmail())
            //         ->subject('Please Confirm your Email')
            //         ->htmlTemplate('registration/confirmation_email.html.twig')
            // );
            // do anything else you need here, like send an email

            return $this->redirectToRoute('home');
        }



        return $this->render('home/index.html.twig', [
            'registrationForm' => $form->createView(),
            'styles' => $styles,
            'artistes' => $artistes
            // 'artist_style' =>$artist_style
        ]);
    }


    /**
     * L'affichage de la page artiste en détail
     * @Route("/decouvrir/{id}", name="artist_view")
     */
    public function view(int $id, Request $request, MailerInterface $mailer): Response
    {
        $em = $this->getDoctrine()->getManager(); // Connexion
        $DetailArtist = $em->getRepository(Artist::class)->find($id); //trouver selon l'ID
        $artistes = $em->getRepository(Artist::class)->findBy(['id'=>$DetailArtist->getId()]); 
            // array(),
            // array('id' => 'DESC'), 1);
        //afficher les styles de l'artiste
        $styles = $em->getRepository(Style::class)->findAll();
        $pictures = $em->getRepository(Style::class)->findBy(['id'=> $DetailArtist->getId()]);
        $instagram = $em->getRepository(Style::class)->findAll();
        $artistsNear = $em->getRepository(Artist::class)->findByCity($DetailArtist->getCity(),$DetailArtist->getId());
   
       
       // Pour contacter un artiste par mail 
        $form = $this->createForm(ContactArtistType::class);

        $contact = $form->handleRequest($request);
       
        if($form->isSubmitted() && $form->isValid()){
           $email = (new TemplatedEmail())
           ->from($contact->get('email')->getData())
           ->to($DetailArtist->getEmail())
           ->subject('Fink: un visiteur souhaite vous contacter! ')
           ->htmlTemplate('emails/contact_artist.html.twig')
           ->context([
               'objet' => $contact->get('title')->getData(),
               'mail' => $contact->get('email')->getData(),
               'message' => $contact->get('message')->getData()
           ]);

          $mailer->send($email);

            // On confirme et on redirige
            $this->addFlash('message', 'Votre e-mail a bien été envoyé');
            return $this->redirectToRoute('artist_view', ['id' => $DetailArtist->getId()]);
        }

        //afficher la page 'detail'
        return $this->render('home/view.html.twig', [
            'DetailArtist' => $DetailArtist,
            'artistes' => $artistes,
            'styles' => $styles,
            'pictures' =>$pictures,
            'artistsNear' => $artistsNear,
            'instagram'=>$instagram,
            'form'     => $form->createView()
        ]);

    }


    /**
     * *Affichage de tous les artistes de la bdd dont le profil est validé par l'admin et publié sur le site, dans l'ordre de création (recent->old)
     * @Route("/gallerie", name="gallerie")
     */
    public function gallerie(Request $request, UserPasswordEncoderInterface $passwordEncoder): Response
    {
        $user = new Artist();
        $form = $this->createForm(RegistrationFormType::class, $user);
        $form->handleRequest($request);

        $entityManager = $this->getDoctrine()->getManager();
        $styles = $entityManager->getRepository(Style::class)->findAll();
        
        //j'affiche les artistes  - de la date de création la plus récent vers la plus vieille avec l'id en AI, same result
        $artistes = $entityManager->getRepository(Artist::class)->findBy(
            array(),
            array('id' => 'DESC')
        );

        if ($form->isSubmitted() && $form->isValid()) {
            // encode the plain password
            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );


            $entityManager->persist($user);
            $entityManager->flush();


            // // generate a signed url and email it to the user
            // $this->emailVerifier->sendEmailConfirmation('app_verify_email', $user,
            //     (new TemplatedEmail())
            //         ->from(new Address('finkart@outlook.fr', 'Fink Art'))
            //         ->to($user->getEmail())
            //         ->subject('Please Confirm your Email')
            //         ->htmlTemplate('registration/confirmation_email.html.twig')
            // );
            // do anything else you need here, like send an email

            return $this->redirectToRoute('home');
        }


        return $this->render('home/gallerie.html.twig', [
            'registrationForm' => $form->createView(),
            'styles' => $styles,
            'artistes' => $artistes
            
        ]);
    }

     /**
     * @Route("/result", name="result")
     */
    public function result(): Response
    {
        // dd($_POST);
        $entityManager = $this->getDoctrine()->getManager();
        $artistes = $entityManager->getRepository(Artist::class)->findBy(['city' => $_REQUEST['city']]);

        $styles = $entityManager->getRepository(Style::class)->findAll();
        

        return $this->render('home/result.html.twig', [
            'artistes' => $artistes,
            'styles' => $styles
        ]);
    } 
}

templates/home/gallerie.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.0.0/css/font-awesome.min.css">
	<script src="https://kit.fontawesome.com/5398383d22.js" crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" defer></script>
	<script src="{{asset('js/search.js')}}"></script>

	<link href="{{ asset('styles/index.css') }}" type="text/css" rel="stylesheet">
	<link href="{{ asset('styles/artistcard.css') }}" type="text/css" rel="stylesheet">
	<link href="{{ asset('styles/gotop.css') }}" type="text/css" rel="stylesheet">
	<link href="{{ asset('styles/gallerie.css') }}" type="text/css" rel="stylesheet">
{% endblock %}
{% block javascripts %}
	<script src="{{ asset('js/gotop.js') }}" defer></script>
{% endblock %}


{% block title %}FINK | Find your INK artist !
{% endblock %}


{% block body %}

	{# ici le header user connected or not #}
	{% block header %}
		{% include 'main/header.html.twig' %}
	{% endblock header %}

<div class="bg-feuille1">
	
	



{# Bouton to the top  #}
	<a id="gotop"></a>

	{# Container principale #}
	<div class="container">
		<div id="meet">
			<div>
				<h3 class="text-center mt-5 mb-5">
					Découvrir tous les <span>artistes</span> Tatoueurs/ses
				</h3>
			</div>
			<!-- CARTE APERCU ARTISTE -->
			<div class="Cartes d-flex flex-wrap justify-content-around">
				<!--  BOUCLE ICI POUR AFFICHAGE ARTISTE -->
					{% for artiste in artistes %}
					<a href="{{ path('artist_view', {'id': artiste.id}) }}">
						 <div class="carte-artiste card">
							<img src={{ asset('/cover_picture/' ~ artiste.CoverPicture) }} alt="Artiste à {{ artiste.city }} : {{ artiste.pseudo }}">
							<div class="info-artiste">
								<div
									class="profil-picture">
									{# ICi l'image de ProfilePicture #}
									<img src={{ asset('/asset/uploads/' ~ artiste.profilePicture) }} alt="{{ artiste.pseudo }}">
								</div>
								<div class="name d-flex justify-content-between">
									<p>{{ artiste.pseudo }}</p>
									<p>
										<i class="fas fa-map-marker-alt"></i>
										{{ artiste.city }}
									</p>
								</div>
								<div class="styles d-inline-flex">
								{# Boucle pour les styles #}
									{% for style in artiste.styles %}
										<p>{{ style.name }}</p>
									{% endfor %}
								</div>
							</div>
						</div>
					</a>
				{% endfor %}
				<!-- FIN DE BOUCLE ARTISTE APERCU -->
			</div> <!-- FIN CARTE APERCU ARTISTE -->
		</div>


	</div>
</div>


	{# ici le footer #}
	{% block footer %}
		{% include 'main/footer.html.twig' %}
	{% endblock footer %}
{% endblock %}

templates/home/index.html.twig
{% extends 'base.html.twig' %}
{% block stylesheets %}
	<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.0.0/css/font-awesome.min.css">
	<script src="https://kit.fontawesome.com/5398383d22.js" crossorigin="anonymous"></script>
	<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
	<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js" defer></script>
	<script src="{{asset('js/search.js')}}"></script>

	<link href="{{ asset('styles/index.css') }}" type="text/css" rel="stylesheet">
	<link href="{{ asset('styles/artistcard.css') }}" type="text/css" rel="stylesheet">
	<link href="{{ asset('styles/gotop.css') }}" type="text/css" rel="stylesheet">
{% endblock %}
{% block javascripts %}
	<script src="{{ asset('js/gotop.js') }}" defer></script>
{% endblock %}


{% block title %}FINK | Find your INK artist !
{% endblock %}


{% block body %}


	{% for flashError in app.flashes('message') %}
		<div class="alert alert-success" role="alert">{{ flashError }}</div>
	{% endfor %}
	<div
		id="home">
		{# ici le header user connected or not #}
		{% block header %}
			{% include 'main/header.html.twig' %}
		{% endblock header %}

		{# Bouton To the Top #}
		<a id="gotop"></a>
		<div
			class="container">

			{# intro #}
			<div id="home-header" class="d-flex">
				<div class="centre align-self-center">
					<div id="intro" class="">
						<div id="titre">
							<h1 class="d-xs-none d-none ">FINK</h1>
							<h2 class="font-phone">FIND YOUR
								<span>
									INK
								</span>
								ARTIST<span>*</span></h2>
						</div>
					</div>

					{# barre de recherche #}
					<div class="row" id="search-info">
						<div id="search" class="d-flex">
							<form
								action="{{ path('result') }}" method="POST" class="flex-wrap d-flex w-100 align-self-center ">

								{# Style(s) #}
								<select class="search-bar col-12 col-sm-12 col-md-5" id="styles" name="styles[]" multiple="multiple" placeholder="Style(s)">
									{% for style in styles %}
										<option value="{{style.id}}">{{style.name}}</option>
									{% endfor %}
								</select>

								{# localisation #}
								<input type="text" class="col-12 col-sm-12 col-md-5" id="search-city" name="city" placeholder="Localisation">
								<button for="submit" class="button-search col-12 col-sm-12 col-md-2">FINK!</button>
							</form>
						</div>
					</div>
					<div class="traduction">
						<p>* Trouvez le tatoueur ou la tatoueuse idéal(e) dans votre style</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	{# Container principale #}
	<div
		class="container">


		{# ils nous ont rejoins #}
		<div id="meet">
			<div>
				<h3 class="text-center">
					LES TATOUEURS QUI VIENNENT DE NOUS
					<span>REJOINDRE</span>
				</h3>
			</div>
			<!-- CARTE APERCU ARTISTE -->
			<div
				class="Cartes d-flex flex-wrap justify-content-around">
				<!--  BOUCLE ICI POUR AFFICHAGE ARTISTE -->
				{% for artiste in artistes %}
					<a href="{{ path('artist_view', {'id': artiste.id}) }}">
						<div class="carte-artiste card">
							<img src={{ asset('/cover_picture/' ~ artiste.CoverPicture) }} alt="Artiste à {{ artiste.city }} : {{ artiste.pseudo }}">
							<div class="info-artiste">
								<div
									class="profil-picture">
									{# ICi l'image de ProfilePicture #}
									<img src={{ asset('/asset/uploads/' ~ artiste.profilePicture) }} alt="{{ artiste.pseudo }}">
								</div>
								<div class="name d-flex justify-content-between">
									<p>{{ artiste.pseudo }}</p>
									<p>
										<i class="fas fa-map-marker-alt"></i>
										{{ artiste.city }}
									</p>
								</div>
								<div
									class="styles d-inline-flex">
									{# Boucle pour les styles #}
									{% for style in artiste.styles %}
										<p>{{ style.name }}</p>
									{% endfor %}
								</div>
							</div>
						</div>
					</a>
				{% endfor %}
				<!-- FIN DE BOUCLE ARTISTE APERCU -->
			</div>
			<!-- FIN CARTE APERCU ARTISTE -->
		</div>
	</div>


	{# ici le footer #}
	{% block footer %}
		{% include 'main/footer.html.twig' %}
	{% endblock footer %}
{% endblock %}

templates/home/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}FINK | Find your INK artist !
{% endblock %}


{% block body %}

{% block header %}
		{% include 'main/header.html.twig' %}
{% endblock header %}
    
    <div class="container">

        <div class="list">
            {% for artiste in artistes %}
				<a href="{{ path('artist_view', {'id': artiste.id}) }}">
					<div class="carte-artiste card">
					{# METTRE IMG CoverPicture ci-dessous: #}
					<img src={{ asset('/asset/uploads/' ~ artiste.CoverPicture) }} alt="Artiste à {{ artiste.city }} : {{ artiste.pseudo }}">
						<div class="info-artiste">
							<div class="profil-picture">
							{# ICi l'image de ProfilePicture #}
								<img src={{ asset('/asset/uploads/' ~ artiste.profilePicture) }} alt="{{ artiste.pseudo }}">
							</div>
							<div class="name d-flex justify-content-between">
								<p>{{ artiste.pseudo }}</p>
								<p><i class="fas fa-map-marker-alt"></i> {{ artiste.city }} </p>
							</div>
							<div class="styles d-inline-flex">
								{% for style in artiste.styles %}
									<p>{{ style.name }}</p>
							  	{% endfor %}
							</div>
						</div>
					</div>
				</a>
				{% endfor %}
        </div>

    </div>


{% block footer %}
		{% include 'main/footer.html.twig' %}
	{% endblock footer %}
{% endblock %}